- repository: autowarefoundation/autoware
  files:
    - source: .github/dependabot.yaml
    - source: .github/workflows/semantic-pull-request.yaml
    - source: .github/workflows/spell-check-differential.yaml
    - source: .markdownlint.yaml
    - source: .prettierrc.yaml
    - source: .yamllint.yaml
